import { componentTypes, validatorTypes } from '@@ddf';
import { transformSelectOptions, handleSchemaFieldChange } from './helper';

const createClassFieldsSchema = (aeClassId, aeTypeOptions, dTypeOptions) => ({
  fields: [
    {
      component: componentTypes.TEXT_FIELD,
      name: 'name',
      id: 'name',
      label: __('Name'),
      isRequired: true,
      validate: [{ type: validatorTypes.REQUIRED }],
      onChange: (e) => handleSchemaFieldChange(aeClassId, e),
    },
    {
      component: componentTypes.SELECT,
      name: 'aetype',
      id: 'type',
      label: __('Type'),
      //   isRequired: true,
      //   validate: [{ type: validatorTypes.REQUIRED }],
      placeholder: __('<Choose>'),
      options: transformSelectOptions(aeTypeOptions),
      includeEmpty: true,
      onChange: (e) => handleSchemaFieldChange(aeClassId, e),
    },
    {
      component: componentTypes.SELECT,
      name: 'datatype',
      id: 'data_type',
      label: __('Data Type'),
      placeholder: __('<Choose>'),
      options: transformSelectOptions(dTypeOptions),
      includeEmpty: true,
      onChange: (e) => handleSchemaFieldChange(aeClassId, e),
    },
    {
      component: componentTypes.TEXT_FIELD,
      name: 'default_value',
      id: 'default_value',
      label: __('Default Value'),
      onChange: (e) => handleSchemaFieldChange(aeClassId, e),
    },
    {
      component: componentTypes.TEXT_FIELD,
      name: 'display_name',
      id: 'display_name',
      label: __('Display Name'),
      onChange: (e) => handleSchemaFieldChange(aeClassId, e),
    },
    {
      component: componentTypes.TEXT_FIELD,
      name: 'description',
      id: 'description',
      label: __('Description'),
      onChange: (e) => handleSchemaFieldChange(aeClassId, e),
    },
    {
      component: componentTypes.CHECKBOX,
      name: 'substitute',
      id: 'sub',
      label: __('Sub'),
      initialValue: true,
      onChange: (e) => handleSchemaFieldChange(aeClassId, e),
    },
    {
      component: componentTypes.TEXT_FIELD,
      name: 'collect',
      id: 'collect',
      label: __('Collect'),
      onChange: (e) => handleSchemaFieldChange(aeClassId, e),
    },
    {
      component: componentTypes.TEXT_FIELD,
      name: 'message',
      id: 'message',
      label: __('Message'),
      // initialValue: 'create',
      onChange: (e) => handleSchemaFieldChange(aeClassId, e),
    },
    {
      component: componentTypes.TEXT_FIELD,
      name: 'on_entry',
      id: 'on_entry',
      label: __('On Entry'),
      onChange: (e) => handleSchemaFieldChange(aeClassId, e),
    },
    {
      component: componentTypes.TEXT_FIELD,
      name: 'on_exit',
      id: 'on_exit',
      label: __('On Exit'),
      onChange: (e) => handleSchemaFieldChange(aeClassId, e),
    },
    {
      component: componentTypes.TEXT_FIELD,
      name: 'on_error',
      id: 'on_error',
      label: __('On Error'),
      onChange: (e) => handleSchemaFieldChange(aeClassId, e),
    },
    {
      component: componentTypes.TEXT_FIELD,
      name: 'max_retries',
      id: 'max_retries',
      label: __('Max Retries'),
      onChange: (e) => handleSchemaFieldChange(aeClassId, e),
    },
    {
      component: componentTypes.TEXT_FIELD,
      name: 'max_time',
      id: 'max_time',
      label: __('Max Time'),
      onChange: (e) => handleSchemaFieldChange(aeClassId, e),
    },
  ],
});

export default createClassFieldsSchema;
